version: "3.9"

services:
  node1:
    build:
      context: ./node1
    ports:
      - "8081:80"
    networks:
      - mynetwork
  node2:
    build:
      context: ./node2
    ports:
      - "8082:80"
    networks:
      - mynetwork
  node3:
    build:
      context: ./node3
    ports:
      - "8083:80"
    networks:
      - mynetwork
  node4:
    build:
      context: ./node1
    ports:
      - "8084:80"
    networks:
      - mynetwork
  node5:
    build:
      context: ./node2
    ports:
      - "8085:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
